### ISSUE TITLE
Nullable annotation should add null to the list of enums

### ISSUE THREAD

**Issue by atkawa7** [reinert/JJSchema#81]
Add null value to enums when nullable is present

**Comment by reinert** [comment]
Thanks for reporting. A PR would be very appreciated.

**Comment by reinert** [comment]
I realized you were using the "enum" attribute, so the best I way to list null as accpeted in an enum using this attribute was to actually map the null string to a null json primitive. Using the @Nullable annotation was not so clear in this case, and kind of counter intuitive. So you should use "null" string in this attribute to achieve the desired result as in [this test](https://github.com/reinert/JJSchema/blob/master/src/test/java/com/github/reinert/jjschema/v1/EnumTest.java#L120). Thanks for contributing.

**Comment by atkawa7** [comment]
@reinert Thanks. Just wondering if you are able to push the release to maven repo

**Comment by can-staxter** [comment]
Hello, 
Here
https://github.com/reinert/JJSchema/blob/master/src/main/java/com/github/reinert/jjschema/JsonSchemaGenerator.java
on line 413:
   // Check if the Nullable annotation is present, and if so, add 'null' to type attr
        Nullable nullable = propertyReflection.getAnnotation(Nullable.class);
        if (nullable != null) {
            if (returnType.isEnum()) {
                ((ArrayNode) schema.get("enum")).add("null");
            } else {
                String oldType = schema.get(TAG_TYPE).asText();
                ArrayNode typeArray = schema.putArray(TAG_TYPE);
                typeArray.add(oldType);
                typeArray.add("null");
            }
        }

when a field of POJO is a nullable enum, it only adds its value to the created schema. 

For example:
for this field:
@Nullable
@JsonProperty( "booking-status" )
private BookingStatus bookingStatus;

When we do this:
com.github.reinert.jjschema.v1.JsonSchemaFactory schemaFactory = new JsonSchemaV4Factory();
schemaFactory.setAutoPutDollarSchema( true );
JsonNode schema = schemaFactory.createSchema( clazz );

It adds this to the schema:
“booking-status”: {
     “enum”: [
       “PROCESSED”,
       “PENDING”,
       null
     ],
     “type”: “string”
   },

But also primitive type null should be added to the type list as It is declared here: https://json-schema.org/understanding-json-schema/reference/generic.html

So, instead of addition above, this should be added for the example:
“booking-status”: {
     “enum”: [
       “PROCESSED”,
       “PENDING”,
       null
     ],
     “type”: [
           “string”,
           “null”
         ]
   },

Because It is not adding "null" primitive type to the type list to the Json schema;
when I do this:

JsonSchemaFactory factory = JsonSchemaFactory.byDefault();
JsonSchema jsonSchema = factory.getJsonSchema( jsonNode );
jsonSchema.validate( jsonNode );

I get this false validation error:
error: instance type (null) does not match any allowed primitive type (allowed: [“string”])
  level: “error”
  schema: {“loadingURI”:“#”,“pointer”:“/properties/booking-status”}
  instance: {“pointer”:“/booking-status”}
  domain: “validation”
  keyword: “type”
  found: “null”
  expected: [“string”]

Can you please add the "null" primitive to the type list for Nullable enums?
